[package]
name = "public_types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
duration-string = { version = "0.3.0", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
serde_json = "1.0.64"
