default_prompt_endpoint: "127.0.0.1"
load_balancing: "round_robin"
timeout_ms: 5000

overrides:
  # confidence threshold for prompt target intent matching
  prompt_target_intent_matching_threshold: 0.7

# should not be here
embedding_provider:
  name: "bge-large-en-v1.5"
  model: "BAAI/bge-large-en-v1.5"

llm_providers:

  - name: open-ai-gpt-4
    api_key: $OPEN_AI_API_KEY
    model: gpt-4
    default: true

prompt_targets:

  - type: function_resolver
    name: interface_down_packet_drop
    description: |
      Checks for packet drops due to interface unavailability like reboots, shutdowns, or maintainence events. It allows filtering the results by timeframes, interface name, region, and packet error thresholds.
    parameters:
      - name: from_time
        description: An optional natural language timeframe (e.g., "past 7 days", "since a month") to define the time range for packet drop analysis.
        required: false
        type: string
      - name: ifname
        description: An optional interface name filter to apply.
        required: false
        type: string
      - name: region
        description: An optional region filter to apply (from the device table).
        required: false
        type: string
      - name: min_in_errors
        description: Minimum number of in_errors to filter results.
        required: false
        type: integer
      - name: max_in_errors
        description: Maximum number of in_errors to filter results.
        required: false
        type: integer
      - name: min_out_errors
        description: Minimum number of out_errors to filter results.
        required: false
        type: integer
      - name: max_out_errors
        description: Maximum number of out_errors to filter results.
        required: false
        type: integer
      - name: min_in_discards
        description: Minimum number of in_discards to filter results.
        required: false
        type: integer
      - name: max_in_discards
        description: Maximum number of in_discards to filter results.
        required: false
        type: integer
      - name: min_out_discards
        description: Minimum number of out_discards to filter results.
        required: false
        type: integer
      - name: max_out_discards
        description: Maximum number of out_discards to filter results.
        required: false
        type: integer
    endpoint:
      cluster: databasehost
      path: /interface_down_packet_drop
    system_prompt: |
      You are responsible for correlating packet drops with interface down events by analyzing packet errors from the given data.

  - type: function_resolver
    name: packet_errors_impact_flow
    description: |
      To find whether packet flows are impacted due to packet errors by correlating the timestamps between the packet errors and the flows. It allows filtering the results by timeframes, interface name, region, and packet error thresholds.
    parameters:
      - name: from_time
        description: An optional natural language timeframe (e.g., "past 7 days", "since a month") to define the time range for the analysis.
        required: false
        type: string
      - name: ifname
        description: An optional interface name filter to apply.
        required: false
        type: string
      - name: region
        description: An optional region filter to apply (from the device table).
        required: false
        type: string
      - name: min_in_errors
        description: Minimum number of in_errors to filter results.
        required: false
        type: integer
      - name: max_in_errors
        description: Maximum number of in_errors to filter results.
        required: false
        type: integer
      - name: min_out_errors
        description: Minimum number of out_errors to filter results.
        required: false
        type: integer
      - name: max_out_errors
        description: Maximum number of out_errors to filter results.
        required: false
        type: integer
      - name: min_in_discards
        description: Minimum number of in_discards to filter results.
        required: false
        type: integer
      - name: max_in_discards
        description: Maximum number of in_discards to filter results.
        required: false
        type: integer
      - name: min_out_discards
        description: Minimum number of out_discards to filter results.
        required: false
        type: integer
      - name: max_out_discards
        description: Maximum number of out_discards to filter results.
        required: false
        type: integer
    endpoint:
      cluster: databasehost
      path: /packet_errors_impact_flow
    system_prompt: |
      You are responsible for finding and correlating packet errors with the packet flows based on timestamps given in the data. This correlation helps identify if packet flows are impacted by packet errors.

clusters:
  databasehost:
    address: server
