services:
  curve:
    image: curvelaboratory/Curve:latest
    ports:
      - "10000:10000"
      - "11000:11000"
      - "12000:12000"
      - "19901:9901"
    volumes:
      - ${CURVE_CONFIG_FILE:-./demos/function_calling/curve _confg.yaml}:/config/curve_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ~/curve_logs:/var/log/
    env_file:
      - stage.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
