services:
  curve:
    image: curve:latest
    ports:
      - "10000:10000"
      - "19901:9901"
    volumes:
      - ${CURVE_CONFIG_FILE:-./demos/function_calling/curve _confg.yaml}:/config/curve_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
    env_file:
      - stage.env
