services:
  curve:
    image: curvelaboratory/Curve:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "11000:11000"
      - "12000:12000"
      - "19901:9901"
    volumes:
      - ${CURVE_CONFIG_FILE:-../demos/weather_forecast/curve_config.yaml}:/app/curve_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ~/curve_logs:/var/log/
    env_file:
      - env.list
    environment:
      - OTEL_TRACING_HTTP_ENDPOINT=http://host.docker.internal:4318/v1/traces
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
