services:
  curve:
    image: curvelaboratory/Curve:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "11000:11000"
      - "12000:12000"
      - "19901:9901"
    volumes:
      - ${CURVE_CONFIG_FILE:-../demos/weather_forecast/curve_config.yaml}:/config/curve_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ./envoy.template.yaml:/config/envoy.template.yaml
      - ./curve_config_schema.yaml:/config/curve_config_schema.yaml
      - ./tools/cli/config_generator.py:/config/config_generator.py
      - ../crates/target/wasm32-wasi/release/llm_gateway.wasm:/etc/envoy/proxy-wasm-plugins/llm_gateway.wasm
      - ../crates/target/wasm32-wasi/release/prompt_gateway.wasm:/etc/envoy/proxy-wasm-plugins/prompt_gateway.wasm
      - ~/curve_logs:/var/log/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?error}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:?error}
