services:
  curve:
    build:
      context: ../
      dockerfile: curve /Dockerfile
    ports:
      - "10000:10000"
      - "18080:9901"
    volumes:
      - ${CURVE_CONFIG_FILE}:/config/curve_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ./curve _log:/var/log/
    depends_on:
      curve_server:
        condition: service_healthy

  curve_server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "18081:80"
    healthcheck:
        test: ["CMD", "curl" ,"http://localhost/healthz"]
        interval: 5s
        retries: 20
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
