services:
  curve:
    image: curvelaboratory/Curve:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "11000:11000"
      - "12000:12000"
      - "19901:9901"
    volumes:
      - ${CURVE_CONFIG_FILE:-../demos/function_calling/curve_config.yaml}:/config/curve_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ~/curve_logs:/var/log/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?error}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:?error}
