services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    hostname: envoy
    ports:
      - "10000:10000"
      - "19901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasi/release:/etc/envoy/proxy-wasm-plugins
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
    depends_on:
      qdrant:
        condition: service_started
      embeddingserver:
        condition: service_healthy

  embeddingserver:
    build:
      context: ../embedding-server
      dockerfile: Dockerfile
    ports:
      - "18080:80"
    healthcheck:
        test: ["CMD", "curl" ,"http://localhost:80/healthz"]
        interval: 5s
        retries: 20

  qdrant:
    image: qdrant/qdrant
    hostname: vector-db
    ports:
      - 16333:6333
      - 16334:6334

  chatbot-ui:
    build:
      context: ../chatbot-ui
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      - CHAT_COMPLETION_ENDPOINT=http://envoy:10000/v1
