
services:

  config_generator:
    build:
      context: ../../
      dockerfile: config_generator/Dockerfile
    volumes:
      - ../../curve /envoy.template.yaml:/usr/src/app/envoy.template.yaml
      - ./curve_config.yaml:/usr/src/app/curve_config.yaml
      - ./generated:/usr/src/app/out

  curve :
    build:
      context: ../../
      dockerfile: curve /Dockerfile
    hostname: curve 
    ports:
      - "10000:10000"
      - "19901:9901"
    volumes:
      - ./generated/envoy.yaml:/etc/envoy/envoy.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ./curve_config.yaml:/config/curve_config.yaml
    depends_on:
      config_generator:
        condition: service_completed_successfully
      server:
        condition: service_healthy
    environment:
      - LOG_LEVEL=debug

  server:
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "18081:80"
    healthcheck:
        test: ["CMD", "curl" ,"http://localhost:80/healthz"]
        interval: 5s
        retries: 20
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./curve_config.yaml:/root/curve_config.yaml
    # Uncomment following lines to enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # runtime: nvidia  # Enables GPU support
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all  # Use all available GPUs


  function_resolver:
    build:
      context: ../../function_resolver
      dockerfile: Dockerfile
    ports:
      - "18082:80"
    healthcheck:
        test: ["CMD", "curl" ,"http://localhost:80/healthz"]
        interval: 5s
        retries: 20
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      # use ollama endpoint that is hosted by host machine (no virtualization)
      - OLLAMA_ENDPOINT=host.docker.internal
      # uncomment following line to use ollama endpoint that is hosted by docker
      # - OLLAMA_ENDPOINT=ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    ports:
      - '11434:11434'
    profiles:
      - manual

  chatbot_ui:
    build:
      context: ../../chatbot_ui
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_COMPLETION_ENDPOINT=http://curve :10000/v1
