default_prompt_endpoint: "127.0.0.1"
load_balancing: "round_robin"
timeout_ms: 5000

llm_providers:

  - name: "open-ai-gpt-4"
    api_key: "$OPEN_AI_API_KEY"
    model: gpt-4

prompt_targets:

  - type: context_resolver
    name: weather_forecast
    few_shot_examples:
      - what is the weather in New York?
      - how is the weather in San Francisco?
      - what is the forecast in Chicago?
    entities:
      - name: city
        required: true
      - name: days
    endpoint:
      cluster: weatherhost
      path: /weather
    system_prompt: |
      You are a helpful weather forecaster. Use weater data that is provided to you. Please following following guidelines when responding to user queries:
      - Use farenheight for temperature
      - Use miles per hour for wind speed

#TODO: add support for adding custom clusters e.g.
    #  clusters:
    #     qdrant:
    #       options:
    #         - address: "qdrant"
    #         - address: "weatherhost"
    #         - port: 6333
