default_prompt_endpoint: "127.0.0.1"
load_balancing: "round_robin"
timeout_ms: 5000

overrides:
  # confidence threshold for prompt target intent matching
  prompt_target_intent_matching_threshold: 0.8

llm_providers:

  - name: open-ai-gpt-4
    api_key: $OPEN_AI_API_KEY
    model: gpt-4
    default: true

prompt_targets:

  - type: function_resolver
    name: top_employees
    description: |
      Allows you to find the top employees in different groups, such as departments, locations, or position. You can rank the employees by different criteria, like salary, yoe, or rating. Returns the best-ranked employees for each group, helping you identify top n in the list.
    parameters:
      - name: grouping
        description: |
          Select how you'd like to group the employees. For example, you can group them by department, location, or their position. The tool will provide the top-ranked employees within each group you choose.
        required: true
        type: string
        enum: [department, location, position]
      - name: ranking_criteria
        required: true
        type: string
        description: |
          Choose how you'd like to rank the employees. You can rank them by their salary, their yoe, or their rating. The tool will sort the employees based on this ranking and return the best ones from each group.
        enum: [salary, yoe, rating]
      - name: top_n
        required: true
        type: integer
        description: |
          Enter how many of the top employees you want to see in each group. For example, if you enter 3, the tool will show you the top 3 employees for each group you selected.
    endpoint:
      cluster: databasehost
      path: /top_employees
    system_prompt: |
      You are responsible for retrieving the top N employees per group ranked by a constraint.

  - type: function_resolver
    name: aggregate_stats
    description: |
       Calculate summary statistics for groups of employees. You can group employees by categories like department or location and then compute totals, averages, or other statistics for specific attributes such as salary or yoe.
    parameters:
      - name: grouping
        description: |
          Choose how you'd like to organize the employees. For example, you can group them by department, location, or position. The tool will calculate the summary statistics for each group.
        required: true
        enum: [department, location, position]
      - name: aggregate_criteria
        description: |
          Select the specific attribute you'd like to analyze. This could be something like salary, yoe, or rating. The tool will calculate the statistic you request for this attribute.
        required: true
        enum: [salary, yoe, rating]
      - name: aggregate_type
        description: |
          Choose the type of statistic you'd like to calculate for the selected attribute. For example, you can calculate the sum, average, minimum, or maximum value for each group.
        required: true
        enum: [SUM, AVG, MIN, MAX]
    endpoint:
      cluster: databasehost
      path: /aggregate_stats
    system_prompt: |
      You help calculate summary statistics for groups of employees. First, organize the employees by the specified grouping (e.g., department, location, or position). Then, compute the requested statistic (e.g., total, average, minimum, or maximum) for a specific attribute like salary, experience, or rating.

clusters:
  databasehost:
    address: server
