services:
  weather_forecast_service:
    build:
      context: ./
    environment:
      - OLTP_HOST=http://jaeger:4317
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "18083:80"

  chatbot_ui:
    build:
      context: ../shared/chatbot_ui
    ports:
      - "18080:8080"
    environment:
      # this is only because we are running the sample app in the same docker container environemtn as curve
      - CHAT_COMPLETION_ENDPOINT=http://host.docker.internal:10000/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./curve_config.yaml:/app/curve_config.yaml

  jaeger:
    build:
      context: ../shared/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    build:
      context: ../shared/prometheus

  grafana:
    build:
      context: ../shared/grafana
    ports:
      - "3000:3000"
