name: Checks

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal
      - name: Run Clippy on curve 
        run: cd curve  && cargo clippy --all-targets --all-features -- -Dwarnings
      - name: Run Clippy on public_types
        run: cd public_types && cargo clippy --all-targets --all-features -- -Dwarnings

  format:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal
      - name: Run Rustfmt on curve 
        run: cd curve  && cargo fmt -p intelligent-prompt-gateway -- --check
      - name: Run Rustfmt on public_types
        run: cd public_types && cargo fmt -p public_types -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal
      - name: Setup | Install wasm toolchain
        run: rustup target add wasm32-wasi
      - name: Build wasm module
        run: cd curve  && cargo build --release --target=wasm32-wasi
      - name: Run Tests on curve 
        run: cd curve  && cargo test
      - name: Run Tests on public_types
        run: cd public_types && cargo test
