name: Static Analysis

on: [push, pull_request]

jobs:
        # Check and Linting are seperate jobs because linting does not fail 
        #when there are errors outside of the changed files in the pr
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
        - run: cd envoyfilter
        - name: Setup | Checkout
          uses: actions/checkout@v4
        - name: Setup | Rust
          run: rustup toolchain install stable --profile minimal
        - name: Run Check
          run: cargo check --lib --bins --examples --all-features

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
        - run: cd envoyfilter
        - name: Setup | Checkout
          uses: actions/checkout@v4
        - name: Setup | Rust
          run: rustup toolchain install stable --profile minimal
        - name: Run Clippy
          run: cargo clippy --all-targets --all-features
    
    format:
        name: Rustfmt
        runs-on: ubuntu-latest
        
        steps:
        - run: cd envoyfilter
        - name: Setup | Checkout
          uses: actions/checkout@v4
        - name: Setup | Rust
          run: rustup toolchain install stable --profile minimal
        - name: Setup | Install Rustfmt
          run: rustup component add rustfmt
        - name: Run Rustfmt
          run: cargo fmt --all -- --check