name: e2e curve tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest-m
    defaults:
      run:
        working-directory: ./tests/curve

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: build curve  docker image
        run: |
          cd ../../ && docker build  -f curve /Dockerfile . -t curvelaboratory/Curve

      - name: start curve
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          docker compose up | tee &> curve.logs &

      - name: wait for curve to be healthy
        run: |
          source common.sh && wait_for_healthz http://localhost:10000/healthz

      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: install test dependencies
        run: |
          poetry install

      - name: run curve tests
        run: |
          poetry run pytest || tail -100 curve.logs

      - name: stop curve docker container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          docker compose down
