name: e2e tests

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest-m
    # runs-on: gh-large-150gb-ssd

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Run e2e tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          python -mvenv venv
          source venv/bin/activate && cd e2e_tests && bash run_e2e_tests.sh
