name: rust tests (prompt and llm gateway)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal

      - name: Setup | Install wasm toolchain
        run: rustup target add wasm32-wasi

      - name: Build wasm module
        run: cargo build --release --target=wasm32-wasi

      - name: Run unit tests
        run: cargo test --lib

      - name: Run integration tests
        run: cargo test --test integration
